### ISSUE TITLE
Unbound Local Error in html_output.py

### ISSUE THREAD

**Issue by Ksherriff** [victoriapascal/gutsmash#1]
Hi,

I am attempting to use GutSmash and have run into this error. Running on Ubuntu 20.04. Using the --minimal, --cb-knownclusters, and --enable-genefunctions options. This is the trace back of the error.

Traceback (most recent call last):
File "run_gutsmash.py", line 9, in
entrypoint()
File "/home/kylacochrane/gutsmash/antismash/main.py", line 126, in entrypoint
sys.exit(main(sys.argv[1:]))
File "/home/kylacochrane/gutsmash/antismash/main.py", line 115, in main
antismash.run_antismash(sequence, options)
File "/home/kylacochrane/gutsmash/antismash/main.py", line 609, in run_antismash
result = _run_antismash(sequence_file, options)
File "/home/kylacochrane/gutsmash/antismash/main.py", line 688, in _run_antismash
write_outputs(results, options)
File "/home/kylacochrane/gutsmash/antismash/main.py", line 408, in write_outputs
html.write(results.records, module_results_per_record, options)
File "/home/kylacochrane/gutsmash/antismash/outputs/html/init.py", line 98, in write
generate_webpage(records, results, options)
File "/home/kylacochrane/gutsmash/antismash/outputs/html/generator.py", line 140, in generate_webpage
html_sections = generate_html_sections(record_layers_with_regions, results_by_record_id, options)
File "/home/kylacochrane/gutsmash/antismash/outputs/html/generator.py", line 103, in generate_html_sections
sections.append(handler.generate_html(region, handler_results, record, options))
File "/home/kylacochrane/gutsmash/antismash/modules/clusterblast/html_output.py", line 43, in generate_html
div = generate_div(region_layer, record_layer, options_layer, "knownclusterblast", tooltip)
UnboundLocalError: local variable 'tooltip' referenced before assignment

**Comment by victoriapascal** [comment]
Sorry for the late response. I believe this issue was solved a month ago, see: https://github.com/victoriapascal/gutsmash/commit/140cb2f8a18f12a4e8850c83267cc0319a04c5c1. Have you been able to run gutSMASH by now already? You can now also try the web server version of it at https://gutsmash.bioinformatics.nl/.

**Comment by Ksherriff** [comment]
Yes I was able to correct the issue.
